# Documentation Metadata
springdoc.openapi.info.title=Users Microservice API
springdoc.openapi.info.version=v0.1
springdoc.openapi.info.description=Microservicio de gestión de usuarios. \
                                   Expone operaciones CRUD de usuarios y roles del sistema.
